spark:
  version: 3.1.2
  hadoop_version: 3.2
  working_dir: /tmp/spark/data
  master_port: 7077
  worker_work_port: 65000
  master_ui_port: 8080
  worker_ui_port: 8085
  download_location: https://archive.apache.org/dist/spark/
  user: "spark"               
  user_groups: []             
  user_shell: "/bin/false"    

  env_extras: {}
  defaults_extras: {}
  defaults_extras_master: {"spark.eventLog.enabled":"true","spark.eventLog.dir":"file://{{ spark_history_dir }}","spark.history.fs.logDirectory":"file://{{ spark_history_dir }}"}
  defaults_extras_nodes: {}
